config/routes.rb
Rails.application.routes.draw do
  root "top#top"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "search" => "searches#search"
  get "get_colors" => "api#get_colors"
  get "get_favorites" => "api#get_favorites"

  resources :colors do
    collection do
      get 'favorites'
    end
  end

  resources :favorites, only: %i[create destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_before_login_header.html.erb
<div class="flex navbar h-16 bg-[#eaf4fc] sticky top-0 z-50">
  <div class="flex-none">
    <div class="drawer">
      <input id="m-drawer" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <label for="m-drawer" class="btn btn-square btn-ghost" id="menu-icon">
        </label>
      </div>
      <div class="drawer-side z-50">
        <label for="m-drawer" aria-label="close sidebar" class="drawer-overlay"></label> 
        <ul class="menu p-4 w-80 min-h-full bg-[#eaf4fc] text-base-content">
          <li><%= link_to(t('colors.index.title'), colors_path) %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="flex-1">
    <%= link_to root_path do %>
      <span class="text-xl text-[#17184b]">JtcpTool</span>
    <% end %>
  </div>
  <div class="justify-end text-[#17184b] mr-4 hover:text-[#b44c97]">
    <%= link_to(t('devise.registrations.new.sign_up'), new_user_registration_path) %>
  </div>
  <div class="justify-end text-[#17184b] mr-4 hover:text-[#b44c97]">
    <%= link_to(t('devise.sessions.new.sign_in'), new_user_session_path) %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger", id="error_messages">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% next if message_type == 'timedout' %>
  <div class="<%= flash_background_color(message_type) %> px-4 py-2 text-white" id="flash">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-[#eaf4fc] text-base-content mt-8">
  <aside>
    <p>Copyright © 2024 - All right reserved</p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<div class="flex navbar h-16 bg-[#eaf4fc] sticky top-0 z-50">
  <div class="flex-none">
    <div class="drawer">
      <input id="m-drawer" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <label for="m-drawer" class="btn btn-square btn-ghost" id="menu-icon">
        </label>
      </div>
      <div class="drawer-side z-50">
        <label for="m-drawer" aria-label="close sidebar" class="drawer-overlay"></label> 
        <ul class="menu p-4 w-80 min-h-full bg-[#eaf4fc] text-base-content">
          <li><%= link_to("色一覧", colors_path) %></li>
          <li><%= link_to("お気に入り", favorites_colors_path) %></li>
          <li><%= link_to("ログアウト", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "ログアウトしますか？"} ) %></li>
          <li><%= link_to("マイページ", edit_user_registration_path) %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="flex-1">
    <%= link_to root_path do %>
      <span class="text-xl text-[#17184b]">JtcpTool</span>
    <% end %>
  </div>
</div>

<%
=begin
%>

<%
  コメントアウト
  ドロップダウンメニュー用(daisyUi)
  <div class="dropdown dropdown-end">
    <div tabindex="0" role="button" class="btn btn-square btn-ghost">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
      </svg>
    </div>
    <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
      <li><a>Item 1</a></li>
      <li><a>Item 2</a></li>
    </ul>
  </div>
%>

<%
=end
%>